on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2

    - id: build
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: 'armv7hl'
        release: '4.1.0.24'
        fix-version: false
        check: false

#    - name: Upload build result
#      uses: actions/upload-artifact@v2
#      with:
#        name: rpms
#        path: RPMS

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS
